In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest, chi2, mutual_info_classif
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_val_score
from sklearn.feature_extraction import text 
from sklearn.metrics import precision_recall_fscore_support
from sklearn import metrics
# from sklearn.model_selection import StratifiedKFold

In [2]:
# import sys
# !conda install --yes --prefix {sys.prefix} numpy
# !conda install --yes --prefix {sys.prefix} scikit-learn
# !conda install --yes --prefix {sys.prefix} sklearn

In [3]:
##### to print multiple outputs from same cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [4]:
file_path = "/Users/tejasvibelsare/Documents/New_gold.xlsx"
train = pd.read_excel(file_path, sheet_name='Sheet1',usecols = "B,H")

In [5]:
len(train)

86

In [6]:
train.columns

Index(['Contents', 'category'], dtype='object')

In [7]:
len(train[train.category == 'allergic'])

45

In [8]:
len(train[train.category == 'infectious'])

41

In [9]:
train.head()

Contents    category
0              My allergies killin my widdle eyes ??    allergic
1    Well think I woke up today with pink eye smh...  infectious
2  Seriously fuck allergies my eyes hurt and itch...    allergic
3                           My eye itchin #allergies    allergic
4  November was hand foot and mouth. December is ...  infectious

In [10]:
## to convert all infectious records to 1 and allergic records to 0
train.loc[train["category"]=='infectious',"category"]=1
train.loc[train["category"]=='allergic',"category"]=0


In [11]:
train.head()

Contents category
0              My allergies killin my widdle eyes ??        0
1    Well think I woke up today with pink eye smh...        1
2  Seriously fuck allergies my eyes hurt and itch...        0
3                           My eye itchin #allergies        0
4  November was hand foot and mouth. December is ...        1

In [12]:
train_x = train["Contents"]
train_y = train["category"]
train_y=train_y.astype('int')
# train_y.todense()

In [13]:
train_x

0                 My allergies killin my widdle eyes ??
1       Well think I woke up today with pink eye smh...
2     Seriously fuck allergies my eyes hurt and itch...
3                              My eye itchin #allergies
4     November was hand foot and mouth. December is ...
5                      Allergies ugh ((MY EYES))!!!!!!!
6                                I have pink eye. Cool.
7                                   I have pink eye fml
8     Know how to feel like a kid again? Get a case ...
9                Allergy season??...my eyes itch so bad
10                       I woke up with Pink Eye wtffff
11                MY ALLERGIES OMG MY EYES I CAN'T DEAL
12    I have pink eye and a kid threw a pencil at me...
13                      Pretty sure I have pink eye. Tf
14    Thanks, Timehop, for reminding me that my kid ...
15                         Ironic I would have pink eye
16                            That kid gave me pink eye
17                         I have pink eye. Awes

In [14]:
tfidf = TfidfVectorizer(min_df=2,stop_words='english')

In [15]:
stop_words = text.ENGLISH_STOP_WORDS
len(stop_words)

318

In [16]:
stop_words

frozenset({'a',
           'about',
           'above',
           'across',
           'after',
           'afterwards',
           'again',
           'against',
           'all',
           'almost',
           'alone',
           'along',
           'already',
           'also',
           'although',
           'always',
           'am',
           'among',
           'amongst',
           'amoungst',
           'amount',
           'an',
           'and',
           'another',
           'any',
           'anyhow',
           'anyone',
           'anything',
           'anyway',
           'anywhere',
           'are',
           'around',
           'as',
           'at',
           'back',
           'be',
           'became',
           'because',
           'become',
           'becomes',
           'becoming',
           'been',
           'before',
           'beforehand',
           'behind',
           'being',
           'below',
           'beside',
           'besides'

In [17]:
## to split the training and testing data
# x_train,x_test,y_train,y_test = train_test_split(train_x, train_y,test_size=0.2,random_state = 4)

In [18]:
# train_x.ndim
# vectorizer = TfidfVectorizer(sublinear_tf=True, max_df=0.5,stop_words='english')
# X_train = vectorizer.fit_transform(data_train.data)

In [19]:
# x_traintfidf = tfidf.fit_transform(x_train)
x_traintfidf = tfidf.fit_transform(train_x)
x_traintfidf.ndim

2

In [20]:
len(tfidf.get_feature_names())


55

In [21]:
tfidf.get_feature_names()
### list of all features


['allergies',
 'allergy',
 'baby',
 'bad',
 'breathe',
 'camp',
 'case',
 'child',
 'cool',
 'damn',
 'drops',
 'eye',
 'eyes',
 'fml',
 'fuck',
 'gave',
 'got',
 'home',
 'hurt',
 'infection',
 'itch',
 'itching',
 'just',
 'kid',
 'kids',
 'like',
 'morning',
 'need',
 'nose',
 'outside',
 'pink',
 'pissed',
 'poor',
 'pretty',
 'puffy',
 'screw',
 'season',
 'seriously',
 'smh',
 'sneezing',
 'son',
 'summer',
 'sure',
 'thank',
 'thanks',
 'think',
 'throat',
 'time',
 'today',
 'tonight',
 'ugh',
 'viral',
 'watering',
 'woke',
 'wtf']

In [22]:
ch2 = SelectKBest(chi2, k=2)
ch2_X_train = ch2.fit_transform(x_traintfidf, train_y)

mutual = SelectKBest(mutual_info_classif, k=3)
mutual_X_train = mutual.fit_transform(x_traintfidf, train_y)

In [23]:
ch2_X_train.shape
mutual_X_train.shape

(86, 2)

(86, 3)

In [24]:
# X_train.inverse_transform(X_train[0])
train_x[0]
# X_train[0]


'My allergies killin my widdle eyes ??'

In [25]:
tfidf.inverse_transform(ch2_X_train[1])

[array(['allergy'], dtype='<U9')]

In [26]:
tfidf.inverse_transform(mutual_X_train[2])

[array(['allergies'], dtype='<U9')]

In [27]:
## all training data converted to vectors
arr = x_traintfidf.toarray()
# arr = np.array(x_traintfidf)
arr.ndim
# x_traintfidf.todense()

2

In [28]:
# to create pipelining
# text_clf_red = Pipeline([('vect', CountVectorizer()), 
#                        ('reducer', SelectKBest(chi2, k=3000)),
#                        ('clf', MultinomialNB())
#                        ])

# text_clf_red.fit(X_train, y_train)
# y_test_pred = text_clf_red.predict(X_test)
# metrics.accuracy_score(y_test, y_test_pred)

In [29]:
modelRandom = RandomForestClassifier(max_depth=3)
modelSVM = svm.SVC(kernel='linear')
modelNaive = GaussianNB()

In [30]:
# modelRandom.fit(X_train, train_y)

In [31]:
# modelSVM.fit(X_train, train_y)

In [32]:
# modelNaive.fit(X_train, train_y)  ###### giving error

In [33]:
## to convert data into integer format
# y_train = y_train.astype('int')
# modelRandom.fit(x_traintfidf,y_train)
# x_testtfidf = tfidf.transform(x_test)
# pred = modelRandom.predict(x_testtfidf)
# len(pred)
# len(x_test)
# actual = np.array(y_test)
# actual

In [34]:
train_y

0     0
1     1
2     0
3     0
4     1
5     0
6     1
7     1
8     1
9     0
10    1
11    0
12    1
13    1
14    1
15    1
16    1
17    1
18    0
19    1
20    0
21    0
22    0
23    0
24    0
25    0
26    1
27    1
28    0
29    0
     ..
56    0
57    1
58    0
59    0
60    1
61    1
62    0
63    1
64    1
65    0
66    1
67    0
68    1
69    1
70    0
71    1
72    1
73    0
74    0
75    1
76    1
77    0
78    0
79    0
80    1
81    0
82    0
83    0
84    1
85    0
Name: category, Length: 86, dtype: int64

In [35]:

modelRandom_crossValidation_ch2_accuracy = cross_val_score(modelRandom, ch2_X_train,train_y, cv=5, scoring='accuracy')
modelSVM_crossValidation_ch2_accuracy = cross_val_score(modelSVM,ch2_X_train,train_y,cv=5,scoring='accuracy')
# modelNaive_crossValidation_ch2_accuracy = cross_val_score(modelNaive,ch2_X_train,train_y, cv=5, scoring='accuracy')


modelRandom_crossValidation_mutual_accuracy = cross_val_score(modelRandom, mutual_X_train,train_y, cv=5, scoring='accuracy')
modelSVM_crossValidation_mutual_accuracy = cross_val_score(modelSVM,mutual_X_train,train_y,cv=5,scoring='accuracy')
# modelNaive_crossValidation_mutual_accuracy = cross_val_score(modelNaive,mutual_X_train,train_y, cv=5, scoring='accuracy')

modelRandom_crossValidation_ch2_f1 = cross_val_score(modelRandom, ch2_X_train,train_y, cv=5, scoring='accuracy')
modelSVM_crossValidation_ch2_f1 = cross_val_score(modelSVM,ch2_X_train,train_y,cv=5,scoring='accuracy')
# modelNaive_crossValidation_ch2_f1 = cross_val_score(modelNaive,ch2_X_train,train_y, cv=5, scoring='accuracy')


modelRandom_crossValidation_mutual_f1 = cross_val_score(modelRandom, mutual_X_train,train_y, cv=5, scoring='accuracy')
modelSVM_crossValidation_mutual_f1 = cross_val_score(modelSVM,mutual_X_train,train_y,cv=5,scoring='accuracy')
# modelNaive_crossValidation_mutual_f1 = cross_val_score(modelNaive,mutual_X_train,train_y, cv=5, scoring='accuracy')


/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The de

In [36]:
modelRandom_crossValidation_ch2_accuracy
modelSVM_crossValidation_ch2_accuracy


array([1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1.])

In [37]:
modelRandom_crossValidation_mutual_accuracy
modelSVM_crossValidation_mutual_accuracy

array([1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1.])

In [38]:
modelRandom_crossValidation_ch2_f1
modelSVM_crossValidation_ch2_f1


array([1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1.])

In [39]:
modelRandom_crossValidation_mutual_f1
modelSVM_crossValidation_mutual_f1

array([1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1.])

In [40]:
### Mean model accuracy of 5 folds
modelRandom_crossValidation_ch2_accuracy.mean()
modelSVM_crossValidation_ch2_accuracy.mean()

1.0

1.0

In [41]:
modelRandom_crossValidation_ch2_f1.mean()
modelSVM_crossValidation_ch2_f1.mean()

1.0

1.0

In [42]:
modelRandom_crossValidation_mutual_accuracy.mean()
modelSVM_crossValidation_mutual_accuracy.mean()

1.0

1.0

In [43]:
modelRandom_crossValidation_mutual_f1.mean()
modelSVM_crossValidation_mutual_f1.mean()

1.0

1.0

In [44]:
# modelNaive_crossValidation.mean()

In [45]:
### Fitting random forest model 
# modelRandom.fit(x_traintfidf, train_y)
modelRandom.fit(ch2_X_train, train_y)
modelRandom.fit(mutual_X_train, train_y)

/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [46]:
### Fitting SVM model 

# modelSVM.fit(x_traintfidf, train_y)
# modelSVM.fit(ch2_X_train, train_y)
modelSVM.fit(mutual_X_train, train_y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [47]:
file_path = "/Users/tejasvibelsare/Documents/Twitter10K.xlsx"
test = pd.read_excel(file_path, sheet_name='Sheet1',usecols = "B")

In [48]:
file_path = "/Users/tejasvibelsare/Documents/Twitter10K.xlsx"
classified_by_crimson= pd.read_excel(file_path, sheet_name='Sheet1',usecols = "L")
classified = classified_by_crimson["classified"]
len(classified)

4799

In [49]:
test.head()
test_x = test["Contents"]
len(test["Contents"])
# classified_by_crimson = test["classified"]

Contents
0  So I'm finally feeling better, just have a bad...
1          I have pink eye in both eyes...this blows
2  Some girl had pink-eye in my school today, and...
3  I bet people think I'm high but I actually jus...
4  @150CENTIMETRES hahahahaha me too, i got an mc...

4799

In [50]:
test_x

0       So I'm finally feeling better, just have a bad...
1               I have pink eye in both eyes...this blows
2       Some girl had pink-eye in my school today, and...
3       I bet people think I'm high but I actually jus...
4       @150CENTIMETRES hahahahaha me too, i got an mc...
5            I'm pretty sure I have fucking pink eye. FML
6       @maggieenglish @emjs44 i would not suggest get...
7       I watched the vlog where @rj4gui4r got pink ey...
8        @ktrenkema I gots pink eye in both of my eyes ??
9       @JDRAMIREZ I just had to put eye allergy drops...
10                                  i have an eye allergy
11      Conjunctivitis in my eye :(   </3\n\n#FML #wor...
12      i couldn't go to tennis tryouts bc i have pink...
13                                    I have pink eye ugh
14      @samanthaleigh_5 ouch. I'm trying to get ready...
15               Oh my Lord my eyes itch!!! ?? #allergies
16                    My mom mad assl she has pink eye ??
17            

In [51]:
# randomModel1 = TfidfVectorizer()

In [52]:
x_traintfidf.ndim

2

In [53]:
testtfidf = tfidf.transform(test_x)
testtfidf.shape

(4799, 55)

In [54]:
##### Finalizing features of test data

# X_test = ch2.transform(testtfidf)

X_test = mutual.transform(testtfidf)
X_test.ndim

2

In [55]:
test_arr = X_test.toarray()
test_arr.shape

(4799, 3)

In [56]:
# test_arr.ndim

In [57]:
# tfidf1 = TfidfVectorizer(min_df=1,stop_words='english')
# # pred = modelRandom.predict(x_testtfidf)

In [58]:
# x_testtfidf = tfidf.transform(test_x)
# x_testtfidf.shape

In [59]:
# test_arr = x_testtfidf.toarray()
# test_arr.ndim

In [60]:
# modelRandom.fit(x_traintfidf,train_y)
# modelSVM.fit(x_traintfidf,train_y)


In [61]:
pred_random = modelRandom.predict(X_test)

In [62]:
pred_random

array([1, 1, 1, ..., 1, 0, 0])

In [63]:
pred_SVM = modelSVM.predict(X_test)

In [64]:
random_accuracy = metrics.accuracy_score(classified, pred_random)

In [65]:
random_accuracy

0.9987497395290685

In [66]:
SVM_accuracy = metrics.accuracy_score(classified, pred_SVM)

In [67]:
SVM_accuracy

0.9916649301937904

In [68]:
#####Random
precision, recall, F1, _ = list(precision_recall_fscore_support(classified, pred_random, beta=1.0, average="binary"))
precision , recall , F1

(0.9950738916256158, 0.9758454106280193, 0.9853658536585366)

In [69]:
#####SVM
precision, recall, F1, _ = list(precision_recall_fscore_support(classified, pred_SVM, beta=1.0, average="binary"))
precision , recall , F1

(0.8436213991769548, 0.9903381642512077, 0.9111111111111112)

In [70]:
# #####Naive
# precision, recall, F1, _ = list(precision_recall_fscore_support(classified, pred_naive, beta=1.0, average="binary"))
# precision , recall , F1

In [71]:
train_x[0]


'My allergies killin my widdle eyes ??'